### ISSUE TITLE
Unexpected input(s) 'exclude', valid inputs are ['']

### ISSUE THREAD

**Issue by ModischFabrications** [nschloe/action-cached-lfs-checkout#19]
I'm trying out your solution after reading https://github.com/actions/checkout/issues/165 , but it seems like the exclude-option doesn't work for me. Can you point out my mistake? 

```
      - name: Checkout 🛎️
        # uses: actions/checkout@v3 # incompatible with git lfs cache (https://github.com/actions/checkout/issues/165#issuecomment-940225299)
        uses: nschloe/action-checkout-with-lfs-cache@v1
        with:
          exclude: "docs/*"
```

-> 
`Warning: Unexpected input(s) 'exclude', valid inputs are ['']`

https://github.com/ModischFabrications/CutSolverFrontend/actions/runs/3340472670/jobs/5530604944
