### ISSUE TITLE
unable to check out private submodule

### ISSUE THREAD

**Issue by maddy-alegra** [nschloe/action-cached-lfs-checkout#38]
Hi! I'm very new to GH Actions so I'm not sure if I'm doing something wrong, but I'm not able to get this action to pull my repo's private submodule.
Before using the cached LFS action, I was able to make it work with checkout by passing in my ssh key like this:
```
- name: Check out repository
  uses: actions/checkout@v4
  with:
    lfs: true
    ssh-key: ${{ secrets.SSH_KEY }}
    submodules: recursive
```
But I didn't see an option to do that for this action. I did try passing in the token, but that didn't end up working.

I also tried running the following step before my checkout, again with no success:
```
- uses: webfactory/ssh-agent@v0.5.4
  with:
    ssh-private-key: |
      ${{ secrets.SSH_KEY }}
```
Here's what my code looks like in its current state, pretty straightforward:
```
- name: Check out repository
  uses: nschloe/action-cached-lfs-checkout@v1
  with:
    submodules: true
``` 
Any help would be appreciated! Not sure if this is something that's supported or if I'll need to come up with a workaround. Thanks in advance :)
