### ISSUE TITLE
include/exclude sequences

### ISSUE THREAD

**Issue by nolan-yoo-miris** [nschloe/action-cached-lfs-checkout#45]
Hi @nschloe, we've been using this for a while and are a big fan -

We were wondering what the intended usage is for including/excluding sequences.

For instance, 

```
    steps:
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1.2.3
        with:
          include: ["folder_a/**", "folder_b/**"]
```

Will give us something like:
> The workflow is not valid. .github/workflows/build.yaml (Line: 138, Col: 20): A sequence was not expected

Any ideas/direction?

Thank you,
Nolan
