### ISSUE TITLE
Would you consider extending this to accept the filter argument?

### ISSUE THREAD

**Issue by Alex-ley-scrub** [nschloe/action-cached-lfs-checkout#48]
Basically I'm using ideas from this to speed up CI/CD: https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/

namely I use something like this for my Docker build and push to ECR step `--filter=blob:none`:

```yml
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # indicates all history for all tags and branches
          filter: "blob:none" # only load the files/objects as/when we need them
          ref: ${{ github.head_ref || github.ref }}
          lfs: false # don't need big LFS files for build_image
```

I personally use `git describe --tags` to tag the image uniquely but in a semi human readable format such as: `5.68.2-184-gde98bd06ce` as I'm sure you're familiar with. I like it because it tells me how many commits ahead of the last release I am but unfortunately that doesn't work with `--depth=1 ` as you don't have the history for this to be calculated from. But I also don't want a fully deep clone/checkout as that is expensive. So this _`blobless clone`_ is perfect for me as it gives the best of both worlds.

It is supported in `actions/checkout@v4`, which you use under the hood, as an optional [input](https://github.com/actions/checkout/blob/v4/action.yml#L60-L64) but you don't expose it as an optional argument for your action [inputs](https://github.com/nschloe/action-cached-lfs-checkout/blob/main/action.yml#L9).

Would you consider this? I could also do a PR if so.

**Comment by Alex-ley-scrub** [comment]
@nschloe PR: https://github.com/nschloe/action-cached-lfs-checkout/pull/49

**Comment by ilan-gold** [comment]
+1

**Comment by Alex-ley-scrub** [comment]
@ilan-gold and anyone else, feel free to use my/our fork for now:
```yaml
      - uses: Scrub-AI/action-cached-lfs-checkout@v1 # actions/checkout@v6
        with:
          fetch-depth: 0 # 0 indicates all history for all tags and branches
          filter: "blob:none" # only load the files/objects as/when we need them
          ref: ${{ github.head_ref || github.ref }}
          # lfs: true
```
